applicationName: contacts
launchingClass: org.objectweb.jac.samples.contacts.Run
aspects: \
  rtti org/objectweb/jac/samples/contacts/rtti.acc true \
  session org/objectweb/jac/samples/contacts/session.acc false \
  persistence org/objectweb/jac/samples/contacts/persistence.acc true \
  gui org/objectweb/jac/samples/contacts/gui.acc true \
  authentication org/objectweb/jac/samples/contacts/authentication.acc false \
  tracing org/objectweb/jac/samples/contacts/tracing.acc false \
  deployment org/objectweb/jac/samples/contacts/deployment.acc false \
  consistency org/objectweb/jac/samples/contacts/consistency.acc false \
  broadcasting org/objectweb/jac/samples/contacts/broadcasting.acc false \
  load-balancing org/objectweb/jac/samples/contacts/load-balancing.acc false

#topology: //localhost/s1 //localhost/s2 

