
applicationName: calcul

launchingClass: org.objectweb.jac.samples.calcul.Run

aspects: \
  rtti org/objectweb/jac/samples/calcul/rtti.acc true \
  tracing org/objectweb/jac/samples/calcul/tracing.acc true \
  gui org/objectweb/jac/samples/calcul/gui.acc true

#  persistence org/objectweb/jac/samples/calcul/persistence.acc true \

#  broadcasting org/objectweb/jac/samples/calcul/broadcasting.acc true \
#  authentication org/objectweb/jac/samples/calcul/authentication.acc false \
#  session org/objectweb/jac/samples/calcul/session.acc false \
#  persistence org/objectweb/jac/samples/calcul/persistence.acc false \
#  deployment org/objectweb/jac/samples/calcul/deployment.acc true \
#  load-balancing org/objectweb/jac/samples/calcul/load-balancing.acc false \

#topology: //localhost/s1 //localhost/s2 
#topology: //localhost/s1

