/**
 * This class delegates to java.util.HashSet
 * This file was automatically generated by JAC (-g option)
 * DO NOT MODIFY
 * Author: Renaud Pawlak (pawlak@cnam.fr)
 */

package org.objectweb.jac.lib.java.util;

import java.io.Serializable;
import java.lang.Cloneable;
import java.util.Collection;
import java.util.Set;
import org.objectweb.jac.util.Strings;

public class HashSet extends java.util.HashSet {

    //private java.util.HashSet delegate = new java.util.HashSet();

    public Object clone() {
        System.out.println("HashSet.clone");
        Object result = null;
        try { 
            result = super.clone(); 
        } catch(Exception e) {
        };
        //((HashSet)result).delegate=(java.util.HashSet)delegate.clone();
        return result;
    }

    public boolean add(Object p0)  {
        return super.add(p0);
    }

    public boolean contains(Object p0) {
        return super.contains(p0);
    }

    public int size() {
        return super.size();
    }

    public java.util.Iterator iterator() {
        return super.iterator();
    }

    public boolean remove(Object p0) {
        return super.remove(p0);
    }

    public void clear() {
        super.clear();
    }

    public boolean isEmpty() {
        return super.isEmpty();
    }

    public boolean removeAll(Collection p0) {
        return super.removeAll(p0);
    }

    public boolean addAll(Collection p0) {
        return super.addAll(p0);
    }

    public Object[] toArray() {
        return super.toArray();
    }

    public Object[] toArray(Object[] p0) {
        return super.toArray(p0);
    }

    public boolean containsAll(Collection p0) {
        return super.containsAll(p0);
    }

    public boolean retainAll(Collection p0) {
        return super.retainAll(p0);
    }

    public boolean equals(Object o) {
        return this == o;
    }

    public int hashCode() {
        return System.identityHashCode(this);
    }

    public String toString() {
        return getClass().getName()+"@"+System.identityHashCode(this);
    }
}
